services:
    Dayploy\DaypiaBundle\Client\DaypiaClientFactory:
        public: true
        class: "Dayploy\\DaypiaBundle\\Client\\DaypiaClientFactory"
        arguments:
            - '@logger'
            - '@Symfony\Contracts\HttpClient\HttpClientInterface'
    Dayploy\DaypiaBundle\Client\DaypiaClient:
        factory: ['@Dayploy\DaypiaBundle\Client\DaypiaClientFactory', 'createClient']
        arguments: [null]
